### PR TITLE
Implement methods for MusicAlbum class

### LINKED ISSUE #27: [1 pts] Implement methods for MusicAlbum class
Implement methods:
- add_item method in the Genre class
     - should take an instance of the Item class as an input
     - should add the input item to the collection of items
     - should add self as a property of the item object (by 
     - using the correct setter from the item object)
- can_be_archived?() in the MusicAlbum class
     - should override the method from the parent class
     - should return true if parent's method returns true AND if on_spotify equals true
     - otherwise, it should return false

### PR DESCRIPTION
**Pull request by oovillagran**
In this branch, I did the following activities:

**Implement methods:**

- add_item method in the Genre class:
     - should take an instance of the Item class as an input.
     - should add the input item to the collection of items.
     - should add self as a property of the item object (by using the correct setter from the item object)
- can_be_archived?() in the MusicAlbum class:
     - should override the method from the parent class.
     - should return true if the parent's method returns true AND if on_spotify equals true.
     - otherwise, it should return false.

This PR closes #27.

### CODE REVIEW

**Comment by zamcham** [comment]
@oovillagran seems like the PR is behind from the main branch, you'll need to resolve the conflicts first

**Review by zamcham — CHANGES_REQUESTED** [review]
@oovillagran  Great job, but looks like the PR is not up to date with the dev branch :)

**Review by zamcham — APPROVED** [review]
Looks good @oovillagran  you can merge now

**Comment by oovillagran** [comment]
Thanks @zamcham!

**Pull request merged**
